paths:
  # [GET] User Summary by User Id
  /user/summary/:id:
    get:
      tags:
        - users
      summary: Find User summary by Id
      parameters:
        - name: id
          in: params
          required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  # [GET] Newsletter Summary by Newsletter Id
  /newsletter/summary/:id:
    get:
      tags:
        - newsletter
      summary: Find Newsletter summary by Id
      parameters:
        - name: id
          in: params
          required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  # [GET] Newsletter Summary Actions by Newsletter Id
  /newsletter/summary/action/:id:
    get:
      tags:
        - newsletter
      summary: Find Newsletter summary actions by Id
      parameters:
        - name: id
          in: params
          required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

schemes:
  - https
  - http
